### ISSUE TITLE
 Task function unit test exception 

### ISSUE THREAD

**Issue by kyohaifeng** [SvetlovA/static-mock#4]
Hi, @SvetlovA ,The following exception occurred when using the function of Setup(Type type, string methodName, Action action)  to unit test a task function, but these is ok when using the function of generic Setup.

<img width="755" alt="キャプチャ" src="https://user-images.githubusercontent.com/48502242/124555932-9d33fc80-de72-11eb-828a-25e8cea450fa.PNG">

**Comment by SvetlovA** [comment]
Hello, @kyohaifeng, Can you tell which OS you run this test? Because I added pipelines to  run tests on different OS(Windows, Ubuntu, MacOS) and I  saw that same issues reproduced on Ubuntu and MacOS, but for Windows is OK https://github.com/SvetlovA/static-mock/actions/runs/1007386703.

**Comment by kyohaifeng** [comment]
Hi, @SvetlovA ,I tested it by Windows OS with X64 and X86 platform，but all of them were Exceptional

**Comment by SvetlovA** [comment]
It depends on many different things. Compiler use some optimizations in Release mode. Also it depends on your processor architecture. Can you send me your processor info like in screen?
![image](https://user-images.githubusercontent.com/20232172/124890703-fa4dc080-dfe0-11eb-83cd-926e946f0086.png)

**Comment by SvetlovA** [comment]
I fixed it. This was error in tests.
Return type of method is Task<int>, but we try to mock int. Ubuntu and MacOS fail tests on run as expected. But it is really interesting Windows behavior, that we can see error only in debug mode.
Fix commit: https://github.com/SvetlovA/static-mock/commit/8b396ff5c0d22d3b3b625dceeb6b4d782808e182
Test results: https://github.com/SvetlovA/static-mock/actions/runs/1011695756

**Comment by kyohaifeng** [comment]
@SvetlovA ,Hi, this is my computer spec.
<img width="356" alt="キャプチャ" src="https://user-images.githubusercontent.com/48502242/125004468-88cf4a00-e094-11eb-87a0-b6e116a512c2.PNG">
